version: "3"
services:
  dash-app:
    build: ./dash_app
    environment:
      - FLASK_ENV=development
    depends_on:
      - redis
      - data-collector
    ports:
      - "8050:8050"
    volumes:
      - ./dash_app:/usr/src/app

  data-collector:
    build: ./data_collector
    depends_on:
      - redis
    volumes:
      - ./data_collector:/usr/src/app

  worker:
    build: 
      context: .
      dockerfile: ./worker/Dockerfile
    depends_on:
      - redis
      - data-collector
    volumes:
        - ./worker:/usr/src/app

  redis:
    image: redis:alpine
